### ISSUE TITLE
craft new name target bug

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#274]
**Describe the bug**
```bash
craft new name target

[FileExistsError]
  [Errno 17] File exists: '.../masonite-app/target'
```
Initially, I don't have a the `target` file. The `craft new` command create new file called `target` with this content:

```
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial
install:
  - pip install masonite-cli
  - craft install
script: python -m pytest
```

So, I created a new folder called `target` and run the same command:
```
craft new name target

[FileNotFoundError]
  [Errno 2] No such file or directory: '.env-example'
```
I'm able to run the app in `target` folder despite the error.
